"""add orders table

Revision ID: 15ad1789e00a
Revises: 3eab2a76ad3e
Create Date: 2026-05-15 01:47:14.548949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15ad1789e00a'
down_revision: Union[str, None] = '3eab2a76ad3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cart_items', sa.JSON(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('final_discount', sa.Float(), nullable=True),
    sa.Column('final_gifts', sa.JSON(), nullable=True),
    sa.Column('delivery_preference', sa.String(), nullable=True),
    sa.Column('carbon_saved_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
