"""initial schema

Revision ID: 3eab2a76ad3e
Revises: 
Create Date: 2026-05-15 00:35:06.654560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3eab2a76ad3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
